/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ItemEvent;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import model.ManipulaArquivo;
import model.PadraoLeitura;
import relacoes.Epimorfismo;
import relacoes.Funcional;
import relacoes.Injetora;
import relacoes.Isomorfismo;
import relacoes.Monomorfismo;
import relacoes.Relacao;
import relacoes.Sobrejetora;
import relacoes.Total;

/**
 *
 * @author asus note
 */
public class Relacoes extends javax.swing.JFrame {

    private DefaultListModel modelConjuntos = new DefaultListModel();

    /**
     * Creates new form Relacoes
     */
    public Relacoes() {
        initComponents();
        conjunto3.setEnabled(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenu1 = new javax.swing.JMenu();
        enderecoArquivo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        voltar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaConjuntos = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        conjunto1 = new javax.swing.JTextField();
        conjunto2 = new javax.swing.JTextField();
        conjunto3 = new javax.swing.JTextField();
        relacaoComposta = new javax.swing.JRadioButton();
        operacoes = new javax.swing.JComboBox<>();
        limparCampos = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        abrirArquivo = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        relacaoFuncional = new javax.swing.JMenuItem();
        relacaoInjetora = new javax.swing.JMenuItem();
        relacaoTotal = new javax.swing.JMenuItem();
        relacaoSobrejetora = new javax.swing.JMenuItem();
        relacaoMonomorfismo = new javax.swing.JMenuItem();
        relacaoEpimorfismo = new javax.swing.JMenuItem();
        relacaoIsomorfismo = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(652, 492));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Caminho do Arquivo:");

        voltar.setText("Voltar");
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });

        listaConjuntos.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        listaConjuntos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaConjuntosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listaConjuntos);

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Lista de Conjuntos");

        relacaoComposta.setText("Relação Composta");
        relacaoComposta.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                relacaoCompostaItemStateChanged(evt);
            }
        });
        relacaoComposta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relacaoCompostaActionPerformed(evt);
            }
        });

        operacoes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<", ">", "=", "x² = y", "√x = y", " " }));

        limparCampos.setText("Limpar Campos");
        limparCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparCamposActionPerformed(evt);
            }
        });

        jMenu2.setText("Arquivo");

        abrirArquivo.setText("Abrir");
        abrirArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirArquivoActionPerformed(evt);
            }
        });
        jMenu2.add(abrirArquivo);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Relações");

        relacaoFuncional.setText("Funcional");
        relacaoFuncional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relacaoFuncionalActionPerformed(evt);
            }
        });
        jMenu3.add(relacaoFuncional);

        relacaoInjetora.setText("Injetora");
        relacaoInjetora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relacaoInjetoraActionPerformed(evt);
            }
        });
        jMenu3.add(relacaoInjetora);

        relacaoTotal.setText("Total");
        relacaoTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relacaoTotalActionPerformed(evt);
            }
        });
        jMenu3.add(relacaoTotal);

        relacaoSobrejetora.setText("Sobrejetora");
        relacaoSobrejetora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relacaoSobrejetoraActionPerformed(evt);
            }
        });
        jMenu3.add(relacaoSobrejetora);

        relacaoMonomorfismo.setText("Monomorfismo");
        relacaoMonomorfismo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relacaoMonomorfismoActionPerformed(evt);
            }
        });
        jMenu3.add(relacaoMonomorfismo);

        relacaoEpimorfismo.setText("Epimorfismo");
        relacaoEpimorfismo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relacaoEpimorfismoActionPerformed(evt);
            }
        });
        jMenu3.add(relacaoEpimorfismo);

        relacaoIsomorfismo.setText("Isomorfismo");
        relacaoIsomorfismo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relacaoIsomorfismoActionPerformed(evt);
            }
        });
        jMenu3.add(relacaoIsomorfismo);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enderecoArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(voltar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE))
                        .addGap(106, 106, 106))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(conjunto1)
                    .addComponent(limparCampos, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(operacoes, 0, 150, Short.MAX_VALUE)
                    .addComponent(conjunto2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(conjunto3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(relacaoComposta, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(84, 84, 84))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(enderecoArquivo)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(conjunto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(conjunto2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(conjunto3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(relacaoComposta)
                            .addComponent(operacoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(limparCampos))
                        .addGap(0, 81, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void preencheListaConjuntos(ArrayList<String> arquivoLido) {
        ArrayList<String> conjuntos = PadraoLeitura.identificaConjuntos(arquivoLido);
        modelConjuntos.removeAllElements();
        listaConjuntos.setModel(modelConjuntos);
        Iterator<String> conjuntosInterador = conjuntos.iterator();
        while (conjuntosInterador.hasNext()) {
            modelConjuntos.addElement(conjuntosInterador.next());
        }

    }

    private void abrirArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirArquivoActionPerformed
        JFileChooser chooser = new JFileChooser();
        FileNameExtensionFilter filtroTXT = new FileNameExtensionFilter("Arquivos TXT", "txt");
        chooser.addChoosableFileFilter(filtroTXT);
        chooser.setAcceptAllFileFilterUsed(false);
        if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            String caminho = chooser.getSelectedFile().getAbsolutePath();
            if (!caminho.toLowerCase().endsWith(".txt")) {
                caminho += ".txt";
            }
            enderecoArquivo.setText(caminho);
            try {
                ArrayList<String> arquivoLido = ManipulaArquivo.abrirArquivo(caminho);
                preencheListaConjuntos(arquivoLido);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Conjuntos.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_abrirArquivoActionPerformed

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        Index tela = new Index();
        tela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_voltarActionPerformed

    private boolean campoVazio() {

        if (conjunto1.getText().equals("") && conjunto2.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Um ou mais campos estão vazios!");
            return false;
        } else if (conjunto1.getText().equals("") || conjunto2.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Um campo esta vazio!");
            return false;
        } else {
            return true;
        }

    }

    private boolean campoVazioComposto() {

        if (conjunto1.getText().equals("") && conjunto2.getText().equals("") && conjunto3.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Um ou mais campos estão vazios!");
            return false;

        } else if (conjunto1.getText().equals("") || conjunto2.getText().equals("") || conjunto3.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Um campo esta vazio!");
            return false;
        } else {
            return true;
        }

    }

    private void relacaoCompostaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_relacaoCompostaItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            conjunto3.setEnabled(true);
        } else if (evt.getStateChange() == ItemEvent.DESELECTED) {
            conjunto3.setEnabled(false);
        }
    }//GEN-LAST:event_relacaoCompostaItemStateChanged

    private void limparCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparCamposActionPerformed
        conjunto1.setText("");
        conjunto2.setText("");
        conjunto3.setText("");
    }//GEN-LAST:event_limparCamposActionPerformed

    private void listaConjuntosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaConjuntosMouseClicked
        if (conjunto1.getText().isEmpty()) {
            conjunto1.setText(listaConjuntos.getSelectedValue());
        } else if (!(conjunto1.getText().isEmpty()) && conjunto2.getText().isEmpty()) {
            conjunto2.setText(listaConjuntos.getSelectedValue());
        } else if (!(conjunto2.getText().isEmpty()) && conjunto3.isEnabled()) {
            conjunto3.setText(listaConjuntos.getSelectedValue());
        }
    }//GEN-LAST:event_listaConjuntosMouseClicked

    private void relacaoFuncionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relacaoFuncionalActionPerformed

        String operacao = "";

        if (operacoes.getSelectedItem().toString().equals("x² = y")) {
            operacao = "quadrado";
        } else if (operacoes.getSelectedItem().toString().equals("√x = y")) {
            operacao = "raizQuadrada";
        } else {
            operacao = operacoes.getSelectedItem().toString();
        }

        if ((conjunto3.isEnabled()) && campoVazioComposto()) {

            Relacao relacao = new Relacao(conjunto1.getText(), conjunto2.getText(), conjunto3.getText(), operacao);
            Funcional.relacaoFuncionalComposta(relacao);
        } else if (campoVazio()) {

            Relacao relacao = new Relacao(conjunto1.getText(), conjunto2.getText(), operacao);
            Funcional.relacaoFuncional(relacao);
        }
    }//GEN-LAST:event_relacaoFuncionalActionPerformed

    private void relacaoInjetoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relacaoInjetoraActionPerformed

        String operacao = "";

        if (operacoes.getSelectedItem().toString().equals("x² = y")) {
            operacao = "quadrado";
        } else if (operacoes.getSelectedItem().toString().equals("√x = y")) {
            operacao = "raizQuadrada";
        } else {
            operacao = operacoes.getSelectedItem().toString();
        }

        //if (campoVazio()) {
        if ((conjunto3.isEnabled()) && campoVazioComposto()) {

            Relacao relacao = new Relacao(conjunto1.getText(), conjunto2.getText(), conjunto3.getText(), operacao);
            Injetora.relacaoInjetoraComposta(relacao);
        } else if (campoVazio()) {

            Relacao relacao = new Relacao(conjunto1.getText(), conjunto2.getText(), operacao);
            Injetora.relacaoInjetora(relacao);
        }
        //}
    }//GEN-LAST:event_relacaoInjetoraActionPerformed

    private void relacaoTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relacaoTotalActionPerformed

        String operacao = "";

        if (operacoes.getSelectedItem().toString().equals("x² = y")) {
            operacao = "quadrado";
        } else if (operacoes.getSelectedItem().toString().equals("√x = y")) {
            operacao = "raizQuadrada";
        } else {
            operacao = operacoes.getSelectedItem().toString();
        }

        //if (campoVazio()) {
        if ((conjunto3.isEnabled()) && campoVazioComposto()) {

            Relacao relacao = new Relacao(conjunto1.getText(), conjunto2.getText(), conjunto3.getText(), operacao);
            Total.relacaoTotalComposta(relacao);
        } else if (campoVazio()) {
            Relacao relacao = new Relacao(conjunto1.getText(), conjunto2.getText(), operacao);
            Total.relacaoTotal(relacao);
        }
        //}
    }//GEN-LAST:event_relacaoTotalActionPerformed

    private void relacaoSobrejetoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relacaoSobrejetoraActionPerformed

        String operacao = "";

        if (operacoes.getSelectedItem().toString().equals("x² = y")) {
            operacao = "quadrado";
        } else if (operacoes.getSelectedItem().toString().equals("√x = y")) {
            operacao = "raizQuadrada";
        } else {
            operacao = operacoes.getSelectedItem().toString();
        }

        //if (campoVazio()) {
        if ((conjunto3.isEnabled()) && campoVazioComposto()) {

            Relacao relacao = new Relacao(conjunto1.getText(), conjunto2.getText(), conjunto3.getText(), operacao);
            Sobrejetora.relacaoSobrejetoraComposta(relacao);
        } else if (campoVazio()) {
            Relacao relacao = new Relacao(conjunto1.getText(), conjunto2.getText(), operacao);
            Sobrejetora.relacaoSobrejetora(relacao);
        }
        //}
    }//GEN-LAST:event_relacaoSobrejetoraActionPerformed

    private void relacaoMonomorfismoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relacaoMonomorfismoActionPerformed

        String operacao = "";

        if (operacoes.getSelectedItem().toString().equals("x² = y")) {
            operacao = "quadrado";
        } else if (operacoes.getSelectedItem().toString().equals("√x = y")) {
            operacao = "raizQuadrada";
        } else {
            operacao = operacoes.getSelectedItem().toString();
        }

        //if (campoVazio()) {
        if ((conjunto3.isEnabled()) && campoVazioComposto()) {

            Relacao relacao = new Relacao(conjunto1.getText(), conjunto2.getText(), conjunto3.getText(), operacao);
            Monomorfismo.relacaoMonomorfismoComposta(relacao);
        } else if (campoVazio()) {
            Relacao relacao = new Relacao(conjunto1.getText(), conjunto2.getText(), operacao);
            Monomorfismo.relacaoMonomorfismo(relacao);
        }
        //}
    }//GEN-LAST:event_relacaoMonomorfismoActionPerformed

    private void relacaoEpimorfismoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relacaoEpimorfismoActionPerformed

        String operacao = "";

        if (operacoes.getSelectedItem().toString().equals("x² = y")) {
            operacao = "quadrado";
        } else if (operacoes.getSelectedItem().toString().equals("√x = y")) {
            operacao = "raizQuadrada";
        } else if (campoVazio()) {
            operacao = operacoes.getSelectedItem().toString();
        }

        //if (campoVazio()) {
        if ((conjunto3.isEnabled()) && campoVazioComposto()) {

            Relacao relacao = new Relacao(conjunto1.getText(), conjunto2.getText(), conjunto3.getText(), operacao);
            Epimorfismo.relacaoEpimorfismoComposta(relacao);
        } else if (campoVazio()) {
            Relacao relacao = new Relacao(conjunto1.getText(), conjunto2.getText(), operacao);
            Epimorfismo.relacaoEpimorfismo(relacao);
        }
        //}
    }//GEN-LAST:event_relacaoEpimorfismoActionPerformed

    private void relacaoIsomorfismoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relacaoIsomorfismoActionPerformed

        String operacao = "";

        if (operacoes.getSelectedItem().toString().equals("x² = y")) {
            operacao = "quadrado";
        } else if (operacoes.getSelectedItem().toString().equals("√x = y")) {
            operacao = "raizQuadrada";
        } else if (campoVazio()) {
            operacao = operacoes.getSelectedItem().toString();
        }

        //if (campoVazio()) {
        if ((conjunto3.isEnabled()) && campoVazioComposto()) {
            Relacao relacao = new Relacao(conjunto1.getText(), conjunto2.getText(), conjunto3.getText(), operacao);
            Isomorfismo.relacaoIsomorfismoComposta(relacao);
        } else if (campoVazio()) {

            Relacao relacao = new Relacao(conjunto1.getText(), conjunto2.getText(), operacao);
            Isomorfismo.relacaoIsomorfismo(relacao);
        }
        //}
    }//GEN-LAST:event_relacaoIsomorfismoActionPerformed

    private void relacaoCompostaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relacaoCompostaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_relacaoCompostaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Relacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Relacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Relacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Relacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Relacoes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem abrirArquivo;
    private javax.swing.JTextField conjunto1;
    private javax.swing.JTextField conjunto2;
    private javax.swing.JTextField conjunto3;
    private javax.swing.JTextField enderecoArquivo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton limparCampos;
    private javax.swing.JList<String> listaConjuntos;
    private javax.swing.JComboBox<String> operacoes;
    private javax.swing.JRadioButton relacaoComposta;
    private javax.swing.JMenuItem relacaoEpimorfismo;
    private javax.swing.JMenuItem relacaoFuncional;
    private javax.swing.JMenuItem relacaoInjetora;
    private javax.swing.JMenuItem relacaoIsomorfismo;
    private javax.swing.JMenuItem relacaoMonomorfismo;
    private javax.swing.JMenuItem relacaoSobrejetora;
    private javax.swing.JMenuItem relacaoTotal;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables
}
